### ISSUE TITLE
Frames fails to compile with vinyl 0.12.3

### ISSUE THREAD

**Issue by adamConnerSax** [acowley/Frames#149]
Frames fails to compile with vinyl 0.12.3

Error Message:
```haskell
src/Frames/Rec.hs:71:21: error:
    • Expected a type, but ‘t’ has kind ‘(GHC.Types.Symbol, *)’
    • In the type ‘t’
      In the first argument of ‘(.)’, namely ‘rput @t’
      In the expression: rput @t . Field
   |
71 | rputField = V.rput @t . Field
   |                     ^
```

Putting a vinyl upper bound of <= 0.12.1 is a temporary workaround but I think the vinyl versioning is wrong since whatever happened in 0.12.3 is obviously breaking...

**Comment by phadej** [comment]
As commented on https://github.com/VinylRecords/Vinyl/pull/139#issuecomment-653201991

As the release of vinyl-0.12.3 is relatively new, I blackisted vinyl-0.12.3. Please re-release it as vinyl-0.13.

**Comment by phadej** [comment]
While on it, I also made revisions to `Frames` itself, e.g. https://hackage.haskell.org/package/Frames-0.6.4/revisions/

Adding

```
base >= 4.10
```

lower bound as GHC.TypeNats is presented only since it. (GHC-8.2). (GHC.TypeLits is since GHC-7.8).

**Comment by acowley** [comment]
I have published `vinyl-0.13.0` and `Frames-0.7.0` that I hope resolve the issue. Thank you for the report, and thanks to @phadej for acting so quickly.

**Comment by phadej** [comment]
Sorry if I was unclear, `Frames` didn't need major bump (based on looking at http://hdiff.luite.com/cgit/Frames/diff?id=0.7.0&id2=0.6.4). Making dependencies bounds stricter is fine even in level-patch release.

I don't know if (some major pieces of) `vinyl` API are re-exported in `Frames`, in that case the "lockstep" versioning is justified.

**Comment by acowley** [comment]
> I don't know if (some major pieces of) vinyl API are re-exported in Frames, in that case the "lockstep" versioning is justified.

This is the case.
